# Generated by Django 6.0.6 on 2026-07-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('orders', '0006_orderstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('completed', 'Completed'), ('chat_message', 'Chat Message')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order'),
        ),
    ]
