# Generated by Django 6.0.6 on 2026-07-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('completed', 'Completed'), ('chat_message', 'Chat Message'), ('new_order', 'New Order'), ('review', 'Review')], max_length=20),
        ),
    ]
