# Generated by Django 6.0.6 on 2026-07-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('chat_message', 'Chat Message'), ('new_order', 'New Order'), ('review', 'Review')], max_length=20),
        ),
    ]
