# Generated by Django 6.0.6 on 2026-06-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='file',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uploaded_at',
        ),
    ]
