# Generated by Django 6.0.6 on 2026-06-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_document_options_document_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='verification_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
