# Generated by Django 6.0.6 on 2026-07-07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisession",
            name="session_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
