export const COUNTRY_CODES = [
  { name: "Egypt", code: "EG", dialCode: "+20" },
  { name: "United States", code: "US", dialCode: "+1" },
  { name: "United Kingdom", code: "GB", dialCode: "+44" },
  { name: "Canada", code: "CA", dialCode: "+1" },
  { name: "Australia", code: "AU", dialCode: "+61" },
  { name: "Germany", code: "DE", dialCode: "+49" },
  { name: "France", code: "FR", dialCode: "+33" },
  { name: "India", code: "IN", dialCode: "+91" },
  { name: "Saudi Arabia", code: "SA", dialCode: "+966" },
  { name: "United Arab Emirates", code: "AE", dialCode: "+971" },
  { name: "Kuwait", code: "KW", dialCode: "+965" },
  { name: "Qatar", code: "QA", dialCode: "+974" },
  { name: "Jordan", code: "JO", dialCode: "+962" },
  { name: "Lebanon", code: "LB", dialCode: "+961" },
  { name: "Turkey", code: "TR", dialCode: "+90" },
];
