# Generated by Django 6.0.6 on 2026-06-08 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default='01002355214', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must contain 7 to 15 digits and may start with +.', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
