# Generated by Django 6.0.6 on 2026-06-15 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_owner'),
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_service_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('estimated_completion_days', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='companies.company')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_offerings', to='procedures.procedure')),
            ],
            options={
                'ordering': ['company_service_fee'],
                'unique_together': {('company', 'procedure')},
            },
        ),
    ]
