# Generated by Django 6.0.6 on 2026-07-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
