# Generated by Django 6.0.6 on 2026-07-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
