# Generated by Django 6.0.6 on 2026-06-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='procedure',
        ),
        migrations.AddField(
            model_name='procedure',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='procedures', to='procedures.requirement'),
        ),
    ]
