# Generated by Django 6.0.6 on 2026-06-14 07:54

import core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('email_verification', 'Email verification'), ('reset_password', 'Reset password')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(default=core.services.generate_otp, max_length=6),
        ),
    ]
