# Generated by Django 6.0.6 on 2026-06-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='governorate',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
